- lambdas/requirements.txt
> [PRMDR-148] pydantic core bug fix

- .github/workflows/full-deploy-all-repository-dispatch.yml
- .github/workflows/full-lambdas-dispatch-deploy.yml
- .github/workflows/full-ui-dispatch-deploy.yml
- .github/workflows/lambdas-dev-to-main-ci.yml
…spatch actions to trigger deployments from the infrastructure repo
> PRMDR_128 dispatch actions

- lambdas/handlers/token_handler.py
- lambdas/tests/unit/handlers/test_token_handler.py
Fix an issue of token handler responds with 500 Internal server error when state given as empty string
> [PRMDR-167][PRMDR-252] 

- lambdas/enums/supported_document_types.py
- lambdas/handlers/create_document_reference_handler.py
Small bugfix to allow create_document_reference_handler.py to run without failing
> [PRMDR-116]

- app/Dockerfile
> updated node version in dockerfile 

- app/src/components/blocks/documentSearchResultsOptions/DocumentSearchResultsOptions.tsx
- app/src/types/pages/UploadDocumentsPage/types.ts
Changes to ensure 'Download all documents' downloads LG and EHR documents instead of just EHR
> PRMDR-396 LG Download bugfix

- app/src/components/blocks/lloydGeorgeRecordDetails/LloydGeorgeRecordDetails.test.tsx
- app/src/components/blocks/lloydGeorgeRecordDetails/LloydGeorgeRecordDetails.tsx
- app/src/pages/lloydGeorgeRecordPage/LloydGeorgeRecordPage.tsx
> FIX [PRMDR-409] change delete link text in more action dropdown

- lambdas/handlers/authoriser_handler.py
- lambdas/handlers/back_channel_logout_handler.py
- lambdas/handlers/bulk_upload_metadata_handler.py
- lambdas/handlers/create_document_reference_handler.py
- lambdas/handlers/delete_document_reference_handler.py
- lambdas/handlers/document_manifest_by_nhs_number_handler.py
- lambdas/handlers/document_reference_search_handler.py
- lambdas/handlers/lloyd_george_record_stitch_handler.py
- lambdas/handlers/login_redirect_handler.py
- lambdas/handlers/logout_handler.py
- lambdas/handlers/search_patient_details_handler.py
- lambdas/handlers/token_handler.py
- lambdas/services/bulk_upload_service.py
- lambdas/services/mock_pds_service.py
- lambdas/services/patient_search_service.py
- lambdas/tests/unit/handlers/test_bulk_upload_metadata_handler.py
- lambdas/tests/unit/handlers/test_logout_handler.py
- lambdas/tests/unit/helpers/data/bulk_upload/test_data.py
- lambdas/tests/unit/utils/decorators/test_set_audit_arg.py
- lambdas/utils/audit_logging_setup.py
- lambdas/utils/decorators/set_audit_arg.py
- lambdas/utils/logging_formatter.py
**Note:** 
The actual changes for this ticket are only in these 2 files:
- lambdas/services/bulk_upload_service.py
- lambdas/tests/unit/helpers/data/bulk_upload/test_data.py
The changes in all other files were just formatter (`make format`) did its job
> [PRMDR-450] 

- .github/workflows/sonarcloud-analysis.yml
> [PRMDR-459]

- Makefile
- lambdas/utils/error_testing_utils.py
Adding init file for sonar scanning
Changes to error testing utils to not show a warning on SonarLint web UI
Adding extra coverage script to makefile as the previous one did not work as expected on my machine, and this one also spits out a nice readable html of the coverage for local test coverage reasons
> PRMDR-459 #2 - Fixes for SonarLint issues

- lambdas/handlers/authoriser_handler.py
- lambdas/models/auth_policy.py
- lambdas/services/authoriser_service.py
- lambdas/services/token_service.py
- lambdas/tests/unit/handlers/test_authoriser_handler.py
- lambdas/tests/unit/services/test_authoriser_service.py
- lambdas/tests/unit/services/test_token_service.py
- lambdas/tests/unit/utils/test_utilities.py
- lambdas/utils/utilities.py
Co-authored-by:  @RachelHowellNHS
> PRMDR-469 Refactor authoriser handler

- lambdas/utils/audit_logging_setup.py
change audit logger to a class var to prevent initiating logger multiple times
> Audit logger bug fix

- app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/view_lloyd_george_not_bsol_workflow.cy.js
> [PRMDR-425-fix] remove assertion and button click that do not fit with e2e journey

- lambdas/tests/unit/utils/test_lloyd_george_validator.py
- lambdas/utils/lloyd_george_validator.py
( temp PR draft to trigger sonar cloud scan)
> PRMDR-611 - Bulk Uploads: Update our GP_ODS checks to allow an All option.

- .github/workflows/base-cypress-build.yml
- .github/workflows/base-jest-test.yml
- .github/workflows/ui-dev-to-main-ci.yml
- .lintstagedrc
- app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/view_lloyd_george_is_bsol_workflow.cy.js
- app/src/components/blocks/lloydGeorgeRecordError/LloydGeorgeRecordError.tsx
- cypress test fix and new test id added for no records title
> Prmdr 658 test

- app/src/components/blocks/lloydGeorgeUploadingStage/LloydGeorgeUploadingStage.tsx
Handle the case of "Retry upload" link button not working when CreateDocRef failed
> PRMDR-757 - Failed uploading correct files & "Retry upload" link not working

- app/src/components/blocks/lloydGeorgeFileInputStage/LloydGeorgeFileInputStage.tsx
- app/src/components/generic/pdfViewer/PdfViewer.tsx
- app/src/components/layout/errorBox/ErrorBox.tsx
- app/src/styles/App.scss
> PRMDR-753: Update keyboard accessible focus states

- lambdas/handlers/update_upload_state_handler.py
- lambdas/services/update_upload_state_service.py
- lambdas/tests/unit/handlers/test_update_upload_state_handler.py
Fixed the http status code that we use in UpdateUploadState Lambda, according to the description in ticket PRMDR-741
> PRMDR-795, PRMDR-796  Fix http status code at UpdateUploadState Lambda

- app/src/components/blocks/_arf/documentSearchResultsOptions/DocumentSearchResultsOptions.test.tsx
- app/src/components/blocks/feedbackForm/FeedbackForm.test.tsx
- app/src/components/blocks/lloydGeorgeRecordStage/LloydGeorgeRecordStage.tsx
- app/src/components/generic/spinner/Spinner.tsx
- app/src/components/generic/spinnerButton/SpinnerButton.test.tsx
- app/src/components/generic/spinnerButton/SpinnerButton.tsx
- app/src/pages/patientSearchPage/PatientSearchPage.test.tsx
Recordings on ticket and branch currently on ndrc
> PRMDR-792 accessibility on loading screens

- app/src/helpers/requests/uploadDocument.test.ts
- app/src/helpers/requests/uploadDocuments.ts
- app/src/pages/lloydGeorgeUploadPage/LloydGeorgeUploadPage.tsx
- lambdas/models/auth_policy.py
- lambdas/models/document_reference.py
- lambdas/models/pds_models.py
- lambdas/models/staging_metadata.py
- lambdas/requirements.txt
- lambdas/scripts/batch_update_ods_code.py
- lambdas/services/create_document_reference_service.py
- lambdas/services/document_reference_search_service.py
- lambdas/services/update_upload_state_service.py
- lambdas/tests/unit/helpers/data/update_upload_state.py
- lambdas/tests/unit/services/test_update_upload_state_service.py
Set upload state to fail on exceeding failed retries:
Set upload state to fail on failed virus scan:
> PRMDR-785: Upload retry logic in the event of upload failure

- lambdas/services/oidc_service.py
> AAL1 auth enablement on pre-prod

- app/src/components/blocks/_delete/deleteSubmitStage/DeleteSubmitStage.test.tsx
- app/src/components/blocks/_delete/deleteSubmitStage/DeleteSubmitStage.tsx
- app/src/pages/documentSearchResultsPage/DocumentSearchResultsPage.tsx
> PRMP-310 - LG "Remove all files" show Spinner button

- lambdas/models/pds_models.py
- lambdas/tests/unit/models/test_pds_models.py
Co-authored-by: Steph Torres <stephane.torres1@nhs.net>
> RMP-751 Bulk Upload: Identify suspended patients

- app/src/components/blocks/_delete/deleteResultStage/DeleteResultStage.tsx
- app/src/components/blocks/_lloydGeorge/lloydGeorgeDownloadComplete/LloydGeorgeDownloadComplete.tsx
Updated p headers to us h2 and h3 on download and delete confirm pages
> [PRMP-1331] Updated p headers to us h2 and h3 on download and delete 

- app/src/components/blocks/_delete/deleteResultStage/DeleteResultStage.tsx
- app/src/components/blocks/_lloydGeorge/lloydGeorgeDownloadComplete/LloydGeorgeDownloadComplete.tsx
Add NHS class to headers from PRMP-1331
> Prmp 1349 - Add NHS class to headers 

- app/cypress/e2e/0-ndr-core-tests/homepage.cy.js
- app/src/components/layout/phaseBanner/PhaseBanner.test.tsx
- app/src/components/layout/phaseBanner/PhaseBanner.tsx
- app/src/styles/App.scss
for 
https://nhse-dsic.atlassian.net/browse/PRMP-1239
> [PRMP-1239] NEW SERVICE updated to be New service

- app/src/styles/App.scss
for
https://nhse-dsic.atlassian.net/browse/PRMP-1237
> [PRMP-1237] Underline nav bar links in the nav bar

- app/Dockerfile
- app/docker/nginx.conf
change config file to hide the server version
> [PRMP-1518] Hide server version

- app/docker/nginx.conf
> [PRMP-1541] CSP Breaks PDF viewer

- app/cypress/e2e/0-ndr-core-tests/privacy_page.cy.js
- app/src/pages/privacyPage/PrivacyPage.test.tsx
- app/src/pages/privacyPage/PrivacyPage.tsx
[PRMP-1602] - update privacy notice content
> [PRMP-1602] Update privacy notice content

- app/cypress/e2e/0-ndr-core-tests/download_lloyd_george_summary.cy.js
- app/cypress/support/routes.ts
- app/src/components/blocks/_arf/selectStage/SelectStage.tsx
- app/src/components/blocks/_arf/uploadSummary/UploadSummary.tsx
- app/src/components/blocks/_delete/deleteSubmitStage/DeleteSubmitStage.tsx
- app/src/components/blocks/_delete/removeRecordStage/RemoveRecordStage.tsx
- app/src/components/blocks/_downloadReport/downloadReportSelectStage/DownloadReportSelectStage.test.tsx
- app/src/components/blocks/_downloadReport/downloadReportSelectStage/DownloadReportSelectStage.tsx
- app/src/components/blocks/_lloydGeorge/lloydGeorgeSelectDownloadStage/LloydGeorgeSelectDownloadStage.tsx
- app/src/components/blocks/_lloydGeorge/lloydGeorgeSelectSearchResults/LloydGeorgeSelectSearchResults.tsx
- app/src/components/blocks/_lloydGeorge/lloydGeorgeViewRecordStage/LloydGeorgeViewRecordStage.tsx
- app/src/components/generic/patientSimpleSummary/PatientSimpleSummary.test.tsx
- app/src/components/generic/patientSimpleSummary/PatientSimpleSummary.tsx
- app/src/components/generic/patientSummary/PatientSummary.test.tsx
- app/src/components/generic/patientSummary/PatientSummary.tsx
- app/src/pages/documentSearchResultsPage/DocumentSearchResultsPage.tsx
- app/src/pages/patientResultPage/PatientResultPage.test.tsx
- app/src/pages/patientResultPage/PatientResultPage.tsx
[PRMP-1468] - implement deceased patient tag and warning message
> [PRMP-1468] Implement deceased patient tag and warning message

- lambdas/models/report/bulk_upload_report_output.py
- lambdas/services/bulk_upload_report_service.py
- lambdas/tests/unit/helpers/data/bulk_upload/expected_bulk_upload_summary_report.csv
- lambdas/tests/unit/helpers/data/bulk_upload/expected_ods_report_for_uploader_1.csv
- lambdas/tests/unit/helpers/data/bulk_upload/expected_ods_report_for_uploader_2.csv
- lambdas/tests/unit/models/test_bulk_upload_report_output.py
- lambdas/tests/unit/services/test_bulk_upload_report_service.py
Improve bulk upload reporting by adding success % to the daily_statistical_bulk_upload_summary_Report
https://nhsd-jira.digital.nhs.uk/browse/PRMT-249
> [PRMT-249] Improve bulk upload reporting by adding success % 

- lambdas/services/pdf_stitching_service.py
- lambdas/tests/unit/services/test_pdf_stitching_service.py
> [PRMT-70] Improve efficiency of LG retrieval

- app/src/styles/App.scss
Small PR to add a new class that's needed for a few different PR's
> [PRME-16] Add new class needed for multiple tickets

- app/src/components/blocks/_documentUpload/documentUploadConfirmStage/DocumentUploadConfirmStage.test.tsx
- app/src/components/blocks/_documentUpload/documentUploadConfirmStage/DocumentUploadConfirmStage.tsx
- app/src/components/generic/pagination/Pagination.test.tsx
- app/src/components/generic/pagination/Pagination.tsx
Design changes and tests for check files page in the Document Upload journey.
https://nhsd-jira.digital.nhs.uk/browse/PRME-74
> [PRME-74] Implement document upload confirmation page

- app/src/components/blocks/_documentUpload/documentSelectOrderStage/DocumentSelectOrderStage.test.tsx
- app/src/components/blocks/_documentUpload/documentSelectOrderStage/DocumentSelectOrderStage.tsx
- app/src/components/blocks/_documentUpload/documentUploadLloydGeorgePreview/DocumentUploadLloydGeorgePreview.test.tsx
- app/src/components/blocks/_documentUpload/documentUploadLloydGeorgePreview/DocumentUploadLloydGeorgePreview.tsx
- app/src/components/blocks/_lloydGeorge/lloydGeorgeFileInputStage/LloydGeorgeFileInputStage.test.tsx
Refactored DocumentSelectOrderStage and DocumentUploadLloydGeorgePreview components and increased unit tests for these componenets.
Localhost on left, Prototype on right - Without files
Localhost on left, Prototype on right - With files
https://nhsd-jira.digital.nhs.uk/browse/PRME-20
> [PRME-20] [Order files] Build details & layout

- app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/view_lloyd_george_workflow.cy.js
- app/src/components/blocks/_documentUpload/documentUploadCompleteStage/DocumentUploadCompleteStage.tsx
- app/src/components/generic/patientSummary/PatientSummary.test.tsx
- app/src/components/generic/patientSummary/PatientSummary.tsx
- app/src/helpers/utils/formatDate.ts
- Fixed typo in Upload confirmation page ("...records and removing...")
- Fixed DOB leading zero (eg: 03 March 1970 -> 3 March 1970)
- Added UT for the DOB get date functionality
- Fixed e2e tests & related missing return types
- [Link to ticket](https://nhsd-jira.digital.nhs.uk/browse/PRME-223)
> [PRME-223] Fix upload prototype discrepancies

- app/cypress/e2e/1-ndr-smoke-tests/gp_user_workflows/patient_search_and_verify_unhappy_workflow.cy.js
- app/src/helpers/utils/errorCodes.ts
- app/src/pages/patientSearchPage/PatientSearchPage.test.tsx
- Updated error code for practice - patient ODS mismatch
- Updated all related unit and smoke tests related to the error code
- Fixed related missing return types
- [link to ticket](https://nhsd-jira.digital.nhs.uk/browse/PRME-139)
> [PRME-139] Practice - Patient ODS mismatch error update
