Makefile, lambdas/handlers/authoriser_handler.py, lambdas/requirements.txt, lambdas/tests/unit/handlers/test_authoriser_handler.py, lambdas/tests/unit/handlers/test_document_reference_search_handler.py
- Add an authoriser lambda which verify and decode a JWT authorizationToken, and respond with IAM policy which allow or deny user access to other APIs
- Add unit test for above lambda
- Change `make zip` command to pack with `--platform manylinux2014_x86_64` flag, as python's cryptography package seems to require some platform specific native library
=> Prmdr 163 migrate authorisation handler

lambdas/enums/supported_document_types.py, lambdas/handlers/create_document_reference_handler.py, lambdas/handlers/document_manifest_by_nhs_number_handler.py, lambdas/services/document_manifest_service.py, lambdas/services/dynamo_service.py, lambdas/services/s3_service.py, lambdas/tests/unit/conftest.py, lambdas/tests/unit/handlers/test_create_document_manifest_by_nhs_number_handler.py, lambdas/tests/unit/handlers/test_create_document_reference_handler.py, lambdas/tests/unit/services/test_document_manifest_service.py, lambdas/tests/unit/services/test_dynamo_service.py, lambdas/tests/unit/services/test_dynamo_service_get_table.py, lambdas/tests/unit/services/test_s3_service.py
- Fix broken function calls in `document_manifest_by_nhs_number_handler`
- Add config to s3 service client for exponential retries
- Refactor duplicate test/env variables to conftest.py
=> [FIX] PRMDR-116 - Fix manifest lambda and add config for exponential retries to s3 service

lambdas/services/lloyd_george_validator.py, lambdas/tests/unit/handlers/test_login_redirect_handler.py
hotfix to resolve a `Runtime.ImportModuleError` encountered in ndrb during testing
related log from cloudwatch:
=> hotfix for Runtime.ImportModuleError

lambdas/services/bulk_upload_service.py, lambdas/tests/unit/services/test_bulk_upload_service.py
- accomodate to recent change in method name in DynamoService `post_item_service` --> `create_item`
- change log level `debug` --> `info` to allow better visibility of error during file copying
- fix a missing argument in method `validate_lg_file_names`
=> Hotfix prmdr 338

lambdas/services/pds_api_service.py, lambdas/tests/unit/services/test_pds_api_service.py
Fix incorrect logic in PDS service related token expiry time comparison, add unit test to verify new logic
A quick look for how this PR will change the token refresh timing:
=> [HOTFIX] [PRMDR-445] 

app/src/components/generic/backButton/BackButton.test.tsx, app/src/components/generic/backButton/BackButton.tsx, app/src/pages/patientSearchPage/PatientSearchPage.test.tsx
Start the login process when the user clicks the back button whilst on the search screen.
If the user is not on the search screen, the back button should take them back one page.
=> Prmdr 452: Back button functionality on the search screens

lambdas/handlers/back_channel_logout_handler.py, lambdas/handlers/logout_handler.py, lambdas/tests/unit/handlers/test_back_channel_logout_handler.py
[CIS2 document](https://digital.nhs.uk/services/care-identity-service/applications-and-services/cis2-authentication/guidance-for-developers/detailed-guidance/session-management#back-channel-logout) mentioned the logout token is sent in a POST body by the application/x-www-form-urlencoded encoding, while our current implementation expects the POST body to be in json format.
This PR would allow extracting logout_token from urlencoded body.
=> Fix back channel logout to handle logout_token as urlencoded format

lambdas/services/bulk_upload_service.py
Changing bulk upload code to ensure that bulk uploaded docs are moved to the appropriate S3 bucket BEFORE any Dynamo data is created about those files in the unlikely event that this will happen
Small log change to keep SonarCloud happy
=> [PRMDR-529]

lambdas/services/login_service.py
add log to show when is_BSOL value may change from true to false depending on whether user_role is gp admin
=> [PRMDR-547] bug fix

app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/download_lloyd_george_workflow.cy.js, app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/view_lloyd_george_workflow.cy.js, app/src/components/blocks/lloydGeorgeRecordDetails/LloydGeorgeRecordDetails.test.tsx, app/src/components/blocks/lloydGeorgeRecordDetails/LloydGeorgeRecordDetails.tsx, app/src/types/blocks/lloydGeorgeActions.ts, app/src/types/blocks/lloydGeorgeStages.ts
removing view all, changing href to placeholder
=> PRMDR-412 - LG action menu fix

lambdas/services/lloyd_george_stitch_service.py, lambdas/tests/unit/handlers/test_lloyd_george_record_stitch_handler.py, lambdas/tests/unit/services/test_lloyd_george_stitch_service.py, lambdas/utils/dynamo_utils.py
- For the stitched LG record pdf, use a random UUID as the file name
- Change the S3 path of stitched LG files from `nhs_number/filename` to `combined_files/filename`, so that URL will not contain patient NHS number anymore
=> PRMDR-881 - Remove personal information from file names of stitched LG record

lambdas/enums/patient_ods_inactive_status.py, lambdas/models/pds_models.py, lambdas/services/search_patient_details_service.py, lambdas/tests/unit/helpers/data/pds/pds_patient_response.py, lambdas/tests/unit/models/test_pds_models.py, lambdas/tests/unit/services/test_search_patient_details_service.py, lambdas/tests/unit/utils/test_ods_utils.py, lambdas/utils/ods_utils.py
Fixed bug where any truthy value for the ODS code would cause a patient to be flagged as active. This caused a problem where PCSE couldn't view suspended patients as their 'ODS code' was returning as `SUSP`, which is considered truthy and was incorrectly flagging them as active. 
Added a unit test with an example expected suspended patient response from PDS
=> [PRMP-839] Fixed suspended patient is active logic & added unit test

app/cypress/e2e/0-ndr-core-tests/privacy_page.cy.js, app/src/pages/privacyPage/PrivacyPage.test.tsx, app/src/pages/privacyPage/PrivacyPage.tsx
In order that users are fully aware of NHS E’s role as data processor, an overview of the National Data Deed and what it means for GP practices is required.
=> [PRMP-767] -  National Data Processing Deed: Communication of Deed and NHSE as Data Processors

lambdas/services/bulk_upload_report_service.py, lambdas/tests/unit/helpers/data/bulk_upload/expected_ods_report_for_uploader_1.csv, lambdas/tests/unit/helpers/data/bulk_upload/expected_ods_report_for_uploader_2.csv, lambdas/tests/unit/services/test_bulk_upload_report_service.py
The "Successful - Deceased" should also be added to the per ODS summary reports, so we can determine a count for all deceased patients uploaded by that ODS code.
=> [PRMP-1065] - Update ODS reports to contain total deceased

app/README.md, app/cypress/e2e/0-ndr-core-tests/feature_flag_workflows/lloyd_george_workflow.cy.js, app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/download_lloyd_george_workflow.cy.js, app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/patient_search_and_verify_workflow.cy.js, app/src/components/blocks/_lloydGeorge/lloydGeorgeViewRecordStage/LloydGeorgeViewRecordStage.tsx, app/src/components/generic/backButton/BackButton.story.ts, app/src/components/generic/backButton/BackButton.test.tsx, app/src/components/generic/backButton/BackButton.tsx, app/src/pages/patientResultPage/PatientResultPage.test.tsx, app/src/pages/patientResultPage/PatientResultPage.tsx
for 
https://nhse-dsic.atlassian.net/browse/PRMP-1321
https://nhse-dsic.atlassian.net/browse/PRMP-1041
=> [PRMP-1321][PRMP-1041] Patient Details screen updates

app/src/components/blocks/_lloydGeorge/lloydGeorgeSelectSearchResults/LloydGeorgeSelectSearchResults.test.tsx, app/src/components/blocks/_lloydGeorge/lloydGeorgeSelectSearchResults/LloydGeorgeSelectSearchResults.tsx
Adjusts how table is read out so that columns don't have mismatched headers
=> [PRM-64] WCAG 3.3.2: missing labels on download checkboxes

.github/workflows/base-vitest-test.yml, .github/workflows/sonarcloud-analysis.yml, README.md, app/Dockerfile, app/README.md, app/package-lock.json, app/package.json
Jira ticket - https://nhsd-jira.digital.nhs.uk/browse/PRM-299
The version of "@types/node" is 22 as this is the latest version available! It is compatible with Node 24.
=> [PRM-299] Update Node.js from v18.x to v24.x

.github/workflows/base-lambdas-reusable-deploy-all.yml
As a result of the changes made in ticket NDR-97, there is a missing condition in the GitHub Action workflow that deploys the "Get Document FHIR" Lambda function. This PR makes sure the "Get Document FHIR" Lambda function is only deployed in the test and development environments.
=> [NDR-180] Missing Condition in GitHub Action for GET FHIR Lambda Deployment

app/cypress/e2e/0-ndr-core-tests/gp_user_workflows/view_lloyd_george_workflow.cy.js, app/src/components/blocks/_arf/selectStage/SelectStage.test.tsx, app/src/components/blocks/_delete/deleteSubmitStage/DeleteSubmitStage.test.tsx, app/src/components/blocks/_delete/deleteSubmitStage/DeleteSubmitStage.tsx, app/src/components/blocks/_documentUpload/documentSelectOrderStage/DocumentSelectOrderStage.test.tsx, app/src/components/blocks/_documentUpload/documentSelectOrderStage/DocumentSelectOrderStage.tsx, app/src/components/blocks/_documentUpload/documentSelectStage/DocumentSelectStage.test.tsx, app/src/components/blocks/_documentUpload/documentSelectStage/DocumentSelectStage.tsx, app/src/components/blocks/_documentUpload/documentUploadConfirmStage/DocumentUploadConfirmStage.test.tsx, app/src/components/blocks/_documentUpload/documentUploadConfirmStage/DocumentUploadConfirmStage.tsx, app/src/components/blocks/_lloydGeorge/lloydGeorgeViewRecordStage/LloydGeorgeViewRecordStage.test.tsx, app/src/components/blocks/_lloydGeorge/lloydGeorgeViewRecordStage/LloydGeorgeViewRecordStage.tsx, app/src/components/blocks/_patientAccessAudit/deceasedPatientAccessAudit/DeceasedPatientAccessAudit.test.tsx, app/src/components/blocks/_patientAccessAudit/deceasedPatientAccessAudit/DeceasedPatientAccessAudit.tsx, app/src/components/blocks/testPanel/TestPanel.tsx, app/src/components/generic/patientSummary/PatientSummary.test.tsx, app/src/components/generic/patientSummary/PatientSummary.tsx, app/src/pages/lloydGeorgeRecordPage/LloydGeorgeRecordPage.test.tsx
Refactored patient summary components and tests
- Replaced PatientSimpleSummary with PatientSummary component across various stages to improve consistency and maintainability.
- Updated tests to reflect changes in patient name formatting and NHS number display.
- Introduced compound component pattern for PatientSummary to allow for more flexible rendering of patient details.
- Improved test coverage for patient summary fields, ensuring proper rendering of NHS number, full name, date of birth.
- Adjusted rendering logic in DocumentSelectStage, DocumentUploadConfirmStage, and DeceasedPatientAccessAudit to utilize the new PatientSummary structure.
Images can be found on the Jira Ticket
https://nhsd-jira.digital.nhs.uk/browse/PRME-115
=> [PRME-115] Patient Summary Changes

app/src/components/blocks/_documentUpload/documentSelectOrderStage/DocumentSelectOrderStage.tsx, app/src/components/blocks/_documentUpload/documentUploadConfirmStage/DocumentUploadConfirmStage.test.tsx, app/src/components/blocks/_documentUpload/documentUploadConfirmStage/DocumentUploadConfirmStage.tsx, app/src/components/blocks/_documentUpload/documentUploadingStage/DocumentUploadingStage.test.tsx, app/src/components/blocks/_documentUpload/documentUploadingStage/DocumentUploadingStage.tsx, app/src/pages/documentUploadPage/DocumentUploadPage.tsx
- Fix startUpload being skipped when there is a single file for upload
`startUpload: () => Promise<void>`
is being called onClick of confirm-button on DocumentUploadConfirmStage which is basically starting the upload process;
currently in main we have a check (that has been commented before) which skips that stage when there is only a single file to upload. this is why the upload process is stuck at 0% (never starts) 
so moving the startUpload call to be first thing inside the DocumentUploadingStage instead;
=> [PRME-170] Move startUpload call into the DocumentUploadingStage

app/src/components/blocks/_downloadReport/downloadReportCompleteStage/DownloadReportCompleteStage.test.tsx, app/src/components/blocks/_downloadReport/downloadReportCompleteStage/DownloadReportCompleteStage.tsx, app/src/components/blocks/_downloadReport/downloadReportSelectStage/DownloadReportSelectStage.test.tsx, app/src/components/blocks/_downloadReport/downloadReportSelectStage/DownloadReportSelectStage.tsx, app/src/pages/patientSearchPage/PatientSearchPage.test.tsx, app/src/pages/patientSearchPage/PatientSearchPage.tsx
- Fix "Return to Home" -> "Go to home" back button text on:
1. Search Page
2. Download Report Select Stage
3. Download Report Complete stage
- Add UT to assert the button text on each page
- Fix related missing return types
- [Link to ticket](https://nhsd-jira.digital.nhs.uk/browse/PRME-222)
=> [PRME-222] Back button text change on Search and Download report pages

app/src/components/blocks/_documentUpload/documentUploadLloydGeorgePreview/DocumentUploadLloydGeorgePreview.test.tsx, app/src/components/blocks/_documentUpload/documentUploadLloydGeorgePreview/DocumentUploadLloydGeorgePreview.tsx
src/components/blocks/_documentUpload/documentUploadLloydGeorgePreview/DocumentUploadLloydGeorgePreview.test.tsx > DocumentUploadCompleteStage > Rendering > renders without documents
An update to DocumentUploadLloydGeorgePreview inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() =>
{   /* fire events that update state */ }
);
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser.
Refactor DocumentUploadLloydGeorgePreview to improve rendering logic and ensure state is cleared when no documents are provided.
=> [PRMP-124] Resolved issue DocumentUploadLloydGeorgePreview tests
